POST http://127.0.0.1:8888/send/message HTTP/1.1
content-type: application/json

{
    "to": "5516991071367",
    "body": "Envio de mensagem nº 28"
}
###
GET http://127.0.0.1:8888/status
###
POST http://127.0.0.1:8888/check/numbers HTTP/1.1
content-type: application/json

{
    "numbers": [
        {"number": "5516900000000", "valid": false, "observation": ""},
        {"number": "5516900000001", "valid": false, "observation": ""},
        {"number": "551690000", "valid": false, "observation": ""}
    ]
}
###

POST http://127.0.0.1:8888/chat HTTP/1.1
content-type: application/json

{
    "text": "Você é o Bob Esponja?"
}
###